<?php

    namespace functional\DataModel;

    use \PHPUnit\Framework\TestCase;
    use \verfriemelt\wrapped\_\Database\Database;
    use \verfriemelt\wrapped\_\Database\Driver\SQLite;
    use \verfriemelt\wrapped\_\DataModel\DataModel;

    class Dummy
    extends DataModel {

        #[ test ]
        public ?int $id = null;

        public ?string $name = null;

        public function getId(): ?int {
            return $this->id;
        }

        public function setId( ?int $id ) {
            $this->id = $id;
            return $this;
        }

        public function getName(): ?string {
            return $this->name;
        }

        public function setName( ?string $name ) {
            $this->name = $name;
            return $this;
        }

    }

    class DataModelTest
    extends TestCase {

        static $connection;

        public static function setUpBeforeClass(): void {
            static::$connection = Database::createNewConnection( 'default', SQLite::class, "", "", "", "", 0 );
        }

        public function setUp(): void {

            switch ( static::$connection::class ) {
                case \verfriemelt\wrapped\_\Database\Driver\Postgres::class:
                    static::$connection->query( 'create table "Dummy" ( id int GENERATED BY DEFAULT AS IDENTITY primary key , name text );' );
                    break;
                case \verfriemelt\wrapped\_\Database\Driver\SQLite::class:
                    static::$connection->query( 'create table "Dummy" ( id integer primary key , name text );' );
                    break;
            }
        }

        public function tearDown(): void {
            static::$connection->query( 'drop table "Dummy" ;' );
        }

        public function saveInstance( $name = 'test' ) {

            $obj = new Dummy;
            $obj->setName( $name );
            $obj->save();

            return $obj;
        }

        public function testObjectSaveAutoGenerateId() {

            $obj = $this->saveInstance();

            $this->assertSame( 1, $obj->getId() );
        }

        public function testObjectGet() {

            $this->saveInstance();
            $newObj = Dummy::get( 1 );

            $this->assertSame( 'test', $newObj->getName() );
        }

        public function testObjectFetch() {

            $this->saveInstance( 'test1' );
            $this->saveInstance( 'test2' );
            $this->saveInstance( 'test3' );

            $newObj = Dummy::findSingle( [ 'id' => 1, 'name' => 'test1' ] );

            $this->assertSame( 'test1', $newObj->getName() );
        }

        public function testObjectFetchWithArray() {

            $this->saveInstance( 'test1' );
            $this->saveInstance( 'test2' );
            $this->saveInstance( 'test3' );

            $newObj = Dummy::findSingle( [ 'id' => [ 1, 2, 3 ], 'name' => 'test2' ] );

            $this->assertSame( 'test2', $newObj->getName() );
        }

        public function testObjectFetchSorted() {

            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );

            $this->assertSame( 3, Dummy::findSingle( [ 'name' => 'test' ], 'id', 'desc' )->getId() );
            $this->assertSame( 1, Dummy::findSingle( [ 'name' => 'test' ], 'id' )->getId() );
        }

        public function testObjectUpdate() {

            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );

            $newObj = Dummy::get( 1 )->setName( 'updated' )->save();

            $this->assertSame( 'test', Dummy::get( 2 )->getName(), 'should not update other objects' );
            $this->assertSame( 'updated', Dummy::get( 1 )->getName(), 'should have updated itself' );
        }

        public function testObjectDelete() {

            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );

            Dummy::get( 1 )->delete();

            $this->assertSame( 2, Dummy::count('id'), 'only two should remain' );
        }

        public function testObjectReload() {

            $obj = new Dummy;
            $obj->setName( 'test' );
            $obj->save();

            Database::getConnection()->query( "update \"Dummy\" set name = 'epic'" );

            $obj->reload();

            $this->assertSame( 'epic', $obj->getName() );
        }

        public function testObjectAll() {

            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );
            $this->saveInstance( 'test' );

            $this->assertSame( 3, count( Dummy::all() ) );
        }

    }
