<?php

declare(strict_types=1);

namespace verfriemelt\wrapped\Tests\Integration\DataModel;

use verfriemelt\wrapped\_\Database\Driver\Postgres;
use verfriemelt\wrapped\_\Database\Driver\SQLite;
use verfriemelt\wrapped\_\DataModel\Attribute\Naming\LowerCase;
use verfriemelt\wrapped\_\DataModel\DataModel;
use verfriemelt\wrapped\_\DataModel\TablenameOverride;
use verfriemelt\wrapped\_\DateTime\DateTime;
use Override;
use verfriemelt\wrapped\Tests\Integration\DatabaseTestCase;

class TypedDummy extends DataModel implements TablenameOverride
{
    protected int $id;
    protected ?string $name = null;
    protected ?DateTime $pubtime = null;
    protected $untyped;

    #[LowerCase]
    public ?DateTime $lastFoundDate = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): static
    {
        $this->id = $id;
        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;
        return $this;
    }

    #[Override]
    public static function fetchTablename(): string
    {
        return 'Dummy';
    }

    public function getPubtime(): ?DateTime
    {
        return $this->pubtime;
    }

    public function setPubtime(?DateTime $pubtime): static
    {
        $this->pubtime = $pubtime;
        return $this;
    }

    public function getUntyped(): mixed
    {
        return $this->untyped;
    }

    public function setUntyped($untyped): static
    {
        $this->untyped = $untyped;
        return $this;
    }

    public function getLastFoundDate(): ?DateTime
    {
        return $this->lastFoundDate;
    }

    public function setLastFoundDate(?DateTime $lastFoundDate): static
    {
        $this->lastFoundDate = $lastFoundDate;
        return $this;
    }
}

class DataModelTypedPropertiesTest extends DatabaseTestCase
{
    #[Override]
    public function setUp(): void
    {
        if (static::$connection instanceof SQLite && static::$connection->getVersion() < 3.35) {
            static::markTestSkipped('returning not supported');
        }

        switch (static::$connection::class) {
            case Postgres::class:
                static::$connection->query(
                    'create table "Dummy" ( id int GENERATED BY DEFAULT AS IDENTITY primary key, name text, pubtime timestamp, untyped text, lastfounddate timestamp );',
                );
                break;
            case SQLite::class:
                if (static::$connection->getVersion() < 3.35) {
                    static::markTestSkipped('nope');
                }

                static::$connection->query(
                    'create table "Dummy" ( id integer primary key not null, name text, pubtime timestamp, untyped text, lastfounddate timestamp );',
                );
                break;
        }
    }

    #[Override]
    public function tearDown(): void
    {
        static::$connection->query('drop table "Dummy" ;');
    }

    public function test_save(): void
    {
        $test = new TypedDummy();
        $test->setPubtime(new DateTime());
        $test->save();

        // read
        $data = TypedDummy::get(1);
        static::assertTrue(is_object($data->getPubtime()));
    }

    public function test_save_with_null(): void
    {
        $test = new TypedDummy();
        $test->save();

        // read
        $data = TypedDummy::get(1);
        static::assertTrue($data->getPubtime() === null);
    }

    public function test_reload_with_time(): void
    {
        $test = new TypedDummy();
        $test->save();

        $secondInstance = TypedDummy::last();

        static::assertSame($test->getId(), $secondInstance->getId());

        static::assertNull($test->getLastFoundDate());
        static::assertNull($secondInstance->getLastFoundDate());

        $test->setLastFoundDate(new DateTime('2012-07-08 11:14:15.889342'));
        $test->save();

        // read updated value
        static::assertNotNull($secondInstance->reload()->getLastFoundDate(), 'should be updated with datetime');
        static::assertSame($secondInstance->getLastFoundDate()->toSqlFormat(), '2012-07-08 11:14:15.889342');

        $test->setLastFoundDate(null);
        $test->save();

        $test->reload();
        static::assertNull($test->getLastFoundDate(), 'original is null');

        // read updated value
        static::assertNull($secondInstance->reload()->getLastFoundDate(), 'should be updated to null again');
    }
}
