<?php

declare(strict_types=1);

namespace verfriemelt\wrapped\_\Http\Response;

class Http
{
    final public const CONTINUE = 100;
    final public const SWITCHING_PROTOCOLS = 101;
    final public const PROCESSING = 102;
    final public const OK = 200;
    final public const CREATED = 201;
    final public const ACCEPTED = 202;
    final public const NON_AUTHORITATIVE_INFORMATION = 203;
    final public const NO_CONTENT = 204;
    final public const RESET_CONTENT = 205;
    final public const PARTIAL_CONTENT = 206;
    final public const MULTI_STATUS = 207;
    final public const ALREADY_REPORTED = 208;
    final public const IM_USED = 226;
    final public const MULTIPLE_CHOICES = 300;
    final public const MOVED_PERMANENTLY = 301;
    final public const FOUND = 302;
    final public const SEE_OTHER = 303;
    final public const NOT_MODIFIED = 304;
    final public const USE_PROXY = 305;
    final public const TEMPORARY_REDIRECT = 307;
    final public const PERMANENT_REDIRECT = 308;
    final public const BAD_REQUEST = 400;
    final public const UNAUTHORIZED = 401;
    final public const PAYMENT_REQUIRED = 402;
    final public const FORBIDDEN = 403;
    final public const NOT_FOUND = 404;
    final public const METHOD_NOT_ALLOWED = 405;
    final public const NOT_ACCEPTABLE = 406;
    final public const PROXY_AUTHENTICATION_REQUIRED = 407;
    final public const REQUEST_TIMEOUT = 408;
    final public const CONFLICT = 409;
    final public const GONE = 410;
    final public const LENGTH_REQUIRED = 411;
    final public const PRECONDITION_FAILED = 412;
    final public const PAYLOAD_TOO_LARGE = 413;
    final public const URI_TOO_LONG = 414;
    final public const UNSUPPORTED_MEDIA_TYPE = 415;
    final public const RANGE_NOT_SATISFIABLE = 416;
    final public const EXPECTATION_FAILED = 417;
    final public const IM_A_TEAPOT = 418;
    final public const UNPROCESSABLE_ENTITY = 422;
    final public const LOCKED = 423;
    final public const FAILED_DEPENDENCY = 424;
    final public const RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL = 425;
    final public const UPGRADE_REQUIRED = 426;
    final public const PRECONDITION_REQUIRED = 428;
    final public const TOO_MANY_REQUESTS = 429;
    final public const REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
    final public const UNAVAILABLE_FOR_LEGAL_REASONS = 451;
    final public const INTERNAL_SERVER_ERROR = 500;
    final public const NOT_IMPLEMENTED = 501;
    final public const BAD_GATEWAY = 502;
    final public const SERVICE_UNAVAILABLE = 503;
    final public const GATEWAY_TIMEOUT = 504;
    final public const HTTP_VERSION_NOT_SUPPORTED = 505;
    final public const VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL = 506;
    final public const INSUFFICIENT_STORAGE = 507;
    final public const LOOP_DETECTED = 508;
    final public const NOT_EXTENDED = 510;
    final public const NETWORK_AUTHENTICATION_REQUIRED = 511;

    final public const STATUS_TEXT = [
        self::CONTINUE => 'Continue',
        self::SWITCHING_PROTOCOLS => 'Switching Protocols',
        self::PROCESSING => 'Processing',
        self::OK => 'OK',
        self::CREATED => 'Created',
        self::ACCEPTED => 'Accepted',
        self::NON_AUTHORITATIVE_INFORMATION => 'Non-Authoritative Information',
        self::NO_CONTENT => 'No Content',
        self::RESET_CONTENT => 'Reset Content',
        self::PARTIAL_CONTENT => 'Partial Content',
        self::MULTI_STATUS => 'Multi-Status',
        self::ALREADY_REPORTED => 'Already Reported',
        self::IM_USED => 'IM Used',
        self::MULTIPLE_CHOICES => 'Multiple Choices',
        self::MOVED_PERMANENTLY => 'Moved Permanently',
        self::FOUND => 'Found',
        self::SEE_OTHER => 'See Other',
        self::NOT_MODIFIED => 'Not Modified',
        self::USE_PROXY => 'Use Proxy',
        self::TEMPORARY_REDIRECT => 'Temporary Redirect',
        self::PERMANENT_REDIRECT => 'Permanent Redirect',
        self::BAD_REQUEST => 'Bad Request',
        self::UNAUTHORIZED => 'Unauthorized',
        self::PAYMENT_REQUIRED => 'Payment Required',
        self::FORBIDDEN => 'Forbidden',
        self::NOT_FOUND => 'Not Found',
        self::METHOD_NOT_ALLOWED => 'Method Not Allowed',
        self::NOT_ACCEPTABLE => 'Not Acceptable',
        self::PROXY_AUTHENTICATION_REQUIRED => 'Proxy Authentication Required',
        self::REQUEST_TIMEOUT => 'Request Timeout',
        self::CONFLICT => 'Conflict',
        self::GONE => 'Gone',
        self::LENGTH_REQUIRED => 'Length Required',
        self::PRECONDITION_FAILED => 'Precondition Failed',
        self::PAYLOAD_TOO_LARGE => 'Payload Too Large',
        self::URI_TOO_LONG => 'URI Too Long',
        self::UNSUPPORTED_MEDIA_TYPE => 'Unsupported Media Type',
        self::RANGE_NOT_SATISFIABLE => 'Range Not Satisfiable',
        self::EXPECTATION_FAILED => 'Expectation Failed',
        self::IM_A_TEAPOT => 'I\'m a teapot',
        self::UNPROCESSABLE_ENTITY => 'Unprocessable Entity',
        self::LOCKED => 'Locked',
        self::FAILED_DEPENDENCY => 'Failed Dependency',
        self::RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL => 'Reserved for WebDAV advanced collections expired proposal',
        self::UPGRADE_REQUIRED => 'Upgrade Required',
        self::PRECONDITION_REQUIRED => 'Precondition Required',
        self::TOO_MANY_REQUESTS => 'Too Many Requests',
        self::REQUEST_HEADER_FIELDS_TOO_LARGE => 'Request Header Fields Too Large',
        self::UNAVAILABLE_FOR_LEGAL_REASONS => 'Unavailable For Legal Reasons',
        self::INTERNAL_SERVER_ERROR => 'Internal Server Error',
        self::NOT_IMPLEMENTED => 'Not Implemented',
        self::BAD_GATEWAY => 'Bad Gateway',
        self::SERVICE_UNAVAILABLE => 'Service Unavailable',
        self::GATEWAY_TIMEOUT => 'Gateway Timeout',
        self::HTTP_VERSION_NOT_SUPPORTED => 'HTTP Version Not Supported',
        self::VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL => 'Variant Also Negotiates (Experimental)',
        self::INSUFFICIENT_STORAGE => 'Insufficient Storage',
        self::LOOP_DETECTED => 'Loop Detected',
        self::NOT_EXTENDED => 'Not Extended',
        self::NETWORK_AUTHENTICATION_REQUIRED => 'Network Authentication Required',
    ];
}
