name: testing
on: push
jobs:
  unit:
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: composer install
      run: composer install

    - name: run tests
      run: |
        DATABASE_DRIVER=none php vendor/bin/phpunit

  int-psql:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_USER: docker
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: composer install
      run: composer install

    - name: run tests
      run: |
        DATABASE_DRIVER=postgres php vendor/bin/phpunit tests/integration
        


  int-sqlite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: composer install
      run: composer install

    - name: run tests
      run: |
        DATABASE_DRIVER=sqlite php vendor/bin/phpunit tests/integration

