name: codepcetion


on: push
jobs:
  check:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_USER: docker
          POSTGRES_DB: docker
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
       
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 8.0
        version: 2
        
    - name: run tests
      run: php vendor/bin/codecept run
