name: linting
on: push
jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: composer install
      run: composer install

    - name: run phpstan
      run: php vendor/bin/phpstan --error-format=github

  csfixer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: composer install
      run: composer install

    - name: run csfixer
      run: vendor/bin/php-cs-fixer fix --diff --dry-run -v

  rector:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: composer install
      run: composer install

    - name: run rector
      run: vendor/bin/rector --dry-run
