name: linting
on: push
jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 8.1
        version: 2

    - name: run phpstan
      run: php vendor/bin/phpstan --error-format=github
